# Generated by Django 5.1.2 on 2024-10-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list_name',
            new_name='item_name',
        ),
    ]
